export default moviesActionsTypes = {
  FETCH_MOVIES: 'FETCH_MOVIES',

  FETCH_MOVIES_LAZYLOAD: 'FETCH_MOVIES_LAZYLOAD',

  FETCH_FRIENDS_MOVIES: 'FETCH_FRIENDS_MOVIES',
  
  FETCH_MOVIES_START: 'FETCH_MOVIES_START'
};