export default userActionsTypes = {

  FETCH_RECOMMENDED_MOVIES: 'FETCH_RECOMMENDED_MOVIES',

  FETCH_RECOMMENDED_MOVIE_DATA: 'FETCH_RECOMMENDED_MOVIE_DATA',

  UPDATE_MOVIES_RECOMMENDED_LOCAL_DATA: 'UPDATE_MOVIES_RECOMMENDED_LOCAL_DATA',

  TOGGLE_FILM_VIEWED_LIST: 'TOGGLE_FILM_VIEWED_LIST',

  TOGGLE_FILM_TO_WATCH_LIST: 'TOGGLE_FILM_TO_WATCH_LIST',

  TOGGLE_USER_LIST: 'TOGGLE_USER_LIST',

  RATE_FILM: 'RATE_FILM',

  DELETE_RATING: 'DELETE_RATING',

  SET_SORT_CRITERION: 'SET_SORT_CRITERION',

  ADD_LIST: 'ADD_LIST',

  DELETE_LIST: 'DELETE_LIST',

  // User profile

  SET_USER_PROFILE: 'SET_USER_PROFILE',

  SET_USER_NOTIFICATIONS_TOKEN: 'SET_USER_NOTIFICATIONS_TOKEN',

  // User friends

  ADD_FRIEND: 'ADD_FRIEND',

  RECOMMEND_FILM_TO_FRIEND: 'RECOMMEND_FILM_TO_FRIEND'
};